import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const questions = [
  { question: "What is the core mechanism behind Circle Cross-Chain Transfer Protocol when transferring USDC across blockchains?", option_a: "Locking USDC on the source chain and minting a wrapped version on the destination chain", option_b: "Burning USDC on the source chain and minting native USDC on the destination chain", option_c: "Bridging liquidity pools between chains using validators", option_d: "Swapping USDC for another token and back again", correct_answer: "Burning USDC on the source chain and minting native USDC on the destination chain" },
  { question: "Who are the co-founders of Circle, the issuer of USDC?", option_a: "Vitalik Buterin and Gavin Wood", option_b: "Jeremy Allaire and Brian Armstrong", option_c: "Sean Neville and Jeremy Allaire", option_d: "Changpeng Zhao and He Yi", correct_answer: "Sean Neville and Jeremy Allaire" },
  { question: "What is USDC primarily designed to be?", option_a: "A governance token", option_b: "A stablecoin pegged to USD", option_c: "A mining coin", option_d: "A meme token", correct_answer: "A stablecoin pegged to USD" },
  { question: "What backs USDC reserves?", option_a: "Gold", option_b: "Crypto only", option_c: "Cash and short-term U.S. Treasuries", option_d: "NFTs", correct_answer: "Cash and short-term U.S. Treasuries" },
  { question: "What best describes the total supply of USDC?", option_a: "It is fixed at 100 billion tokens", option_b: "It is capped and decreases over time", option_c: "It fluctuates based on minting and redemption demand", option_d: "It is controlled solely by validators", correct_answer: "It fluctuates based on minting and redemption demand" },
  { question: "USDC is considered:", option_a: "Algorithmic stablecoin", option_b: "Fiat-backed stablecoin", option_c: "Meme coin", option_d: "Privacy coin", correct_answer: "Fiat-backed stablecoin" },
  { question: "What company built the Arc blockchain network?", option_a: "Coinbase", option_b: "Circle Internet Group", option_c: "Tether", option_d: "Binance", correct_answer: "Circle Internet Group" },
  { question: "What token does Arc use as its native gas fee currency?", option_a: "ETH", option_b: "BTC", option_c: "USDC", option_d: "SOL", correct_answer: "USDC" },
  { question: "What is Arc's consensus mechanism called?", option_a: "Proof of Work (POW)", option_b: "Proof of Stake (POS)", option_c: "Malachite", option_d: "Tendermint", correct_answer: "Malachite" },
  { question: "How does Arc describe itself in terms of its role?", option_a: "The DeFi Chain", option_b: "The Economic OS for the Internet", option_c: "The Gaming Blockchain", option_d: "The Privacy Chain", correct_answer: "The Economic OS for the Internet" },
  { question: "When did Arc launch its public testnet?", option_a: "January 2025", option_b: "June 2025", option_c: "October 2025", option_d: "March 2026", correct_answer: "October 2025" },
  { question: "Which of the following is NOT a listed use case for Arc?", option_a: "Cross-border payments", option_b: "Foreign exchange (FX)", option_c: "NFT gaming marketplace", option_d: "Capital markets", correct_answer: "NFT gaming marketplace" },
  { question: "What type of blockchain is Arc in terms of EVM compatibility?", option_a: "EVM-compatible", option_b: "Non-EVM", option_c: "Cosmos SDK-based", option_d: "Solana Virtual Machine", correct_answer: "EVM-compatible" },
  { question: "What is the transaction finality speed Arc targets?", option_a: "10 seconds", option_b: "5 minutes", option_c: "micro-second speed", option_d: "sub-second finality", correct_answer: "sub-second finality" },
  { question: "Which major institutions are among Arc's testnet participants?", option_a: "Apple and Tesla", option_b: "BlackRock, Visa, and Goldman Sachs", option_c: "Meta and Google", option_d: "JPMorgan alone", correct_answer: "BlackRock, Visa, and Goldman Sachs" },
  { question: "What future security feature is Arc building into its mainnet from day one?", option_a: "Quantum-resistant wallet signatures", option_b: "Zero-knowledge proofs only", option_c: "Biometric authentication", option_d: "Multi-party computation only", correct_answer: "Quantum-resistant wallet signatures" },
  { question: "Which AI company is building developer tools on Arc using its Agent SDK?", option_a: "OpenAI", option_b: "Google DeepMind", option_c: "Anthropic", option_d: "Mistral", correct_answer: "Anthropic" },
  { question: "What is Arc's StableFX feature designed for?", option_a: "NFT minting", option_b: "Real-time onchain stablecoin foreign exchange", option_c: "Token staking rewards that generate yield on reserves", option_d: "Yield farming", correct_answer: "Real-time onchain stablecoin foreign exchange" },
  { question: "Which cross-chain protocols connect Arc to other blockchain networks?", option_a: "Polygon Bridge and Hop", option_b: "Across, Stargate, and Wormhole", option_c: "Synapse and Celer", option_d: "Multichain and Nomad", correct_answer: "Across, Stargate, and Wormhole" },
  { question: "What privacy feature does Arc offer users?", option_a: "Mandatory full privacy", option_b: "Fixed privacy mode for all transactions", option_c: "No privacy options", option_d: "Opt-in configurable privacy for confidential balances", correct_answer: "Opt-in configurable privacy for confidential balances" },
  { question: "What is the key advantage of using USDC as Arc's gas token for businesses?", option_a: "Higher transaction speeds", option_b: "Predictable, dollar-denominated fees without volatility", option_c: "Free transactions always", option_d: "Anonymous payments", correct_answer: "Predictable, dollar-denominated fees without volatility" },
  { question: "Which DEX protocols are participating in Arc's ecosystem?", option_a: "SushiSwap and PancakeSwap only", option_b: "Curve, Uniswap, and Fluid", option_c: "dYdX and Hyperliquid only", option_d: "Serum and Orca only", correct_answer: "Curve, Uniswap, and Fluid" },
  { question: "What does Arc's roadmap include for enshrined paymasters?", option_a: "Only ETH as gas", option_b: "EURC and other stablecoins as gas alternatives", option_c: "Government-issued CBDCs only", option_d: "Bitcoin only", correct_answer: "EURC and other stablecoins as gas alternatives" },
  { question: "When was Arc mainnet beta scheduled for launch?", option_a: "Early 2027", option_b: "2025", option_c: "2026", option_d: "2028", correct_answer: "2026" },
  { question: "What threat does Arc's post-quantum design specifically address for validators?", option_a: "Quantum computers breaking public-key cryptography", option_b: "Front-running by MEV bots", option_c: "51% attacks", option_d: "Sybil attacks", correct_answer: "Quantum computers breaking public-key cryptography" },
  { question: "When does the Arc Discord Office Hours hold?", option_a: "First Wednesday every month", option_b: "Every Tuesday", option_c: "First Tuesday every month", option_d: "Every Wednesday", correct_answer: "Every Tuesday" },
  { question: "Who is the Director of Community at Circle and Arc?", option_a: "Michael Saylor", option_b: "Samson Mcphilly", option_c: "Sam Sealey", option_d: "Timothy Baker", correct_answer: "Sam Sealey" },
  { question: "What is CCTP and what mechanism does it use to move USDC across chains?", option_a: "A bridge that locks tokens and issues wrapped versions", option_b: "A burn-and-mint protocol for native 1:1 transfers", option_c: "A liquidity pool-based swap", option_d: "A centralized custodian transfer", correct_answer: "A burn-and-mint protocol for native 1:1 transfers" },
  { question: "How many blockchain networks does USDC natively support as of late 2025?", option_a: "5", option_b: "12", option_c: "28+", option_d: "50", correct_answer: "28+" },
  { question: "What is the Circle Reserve Fund (USDXX)?", option_a: "A hedge fund run by Circle", option_b: "An SEC-registered 2a-7 government money market fund backing USDC", option_c: "A Bitcoin treasury", option_d: "A DeFi yield vault", correct_answer: "An SEC-registered 2a-7 government money market fund backing USDC" },
  { question: "Which of these is building a social-first liquidity and payment layer on Arc?", option_a: "Xylonet", option_b: "KeplarDAO", option_c: "Ehos", option_d: "OmniSwap", correct_answer: "Xylonet" },
  { question: "What new capability did CCTP V2 introduce that V1 lacked?", option_a: "Support for Ethereum only", option_b: "Fast Transfer (faster-than-finality) and Hooks for post-transfer automation", option_c: "Wrapping of non-USDC tokens", option_d: "Centralized settlement", correct_answer: "Fast Transfer (faster-than-finality) and Hooks for post-transfer automation" },
  { question: "What is Circle's Gateway product?", option_a: "A centralized exchange", option_b: "A unified USDC balance accessible across 11+ chains without manual bridging", option_c: "A hardware wallet", option_d: "A fiat on-ramp only", correct_answer: "A unified USDC balance accessible across 11+ chains without manual bridging" },
  { question: "Approximately how much USDC was in circulation as of March 2026?", option_a: "$10 billion", option_b: "$30 billion", option_c: "$77 billion", option_d: "$200 billion", correct_answer: "$77 billion" },
  { question: "What was the cumulative volume CCTP processed by November 2025?", option_a: "$500 million", option_b: "$5 billion", option_c: "Over $110 billion", option_d: "$1 trillion", correct_answer: "Over $110 billion" },
  { question: "What is EURC?", option_a: "A Euro-pegged stablecoin issued by Circle", option_b: "A European central bank digital currency", option_c: "A DeFi governance token", option_d: "An algorithmic stablecoin", correct_answer: "A Euro-pegged stablecoin issued by Circle" },
  { question: "What company manages and custodies the Circle Reserve Fund portfolio?", option_a: "Goldman Sachs", option_b: "JPMorgan", option_c: "BlackRock at BNY Mellon", option_d: "Fidelity", correct_answer: "BlackRock at BNY Mellon" },
  { question: "What is Circle's CPN (Circle Payments Network) primarily designed for?", option_a: "NFT trading", option_b: "Cross-border payment connectivity for financial institutions", option_c: "Retail crypto trading", option_d: "DeFi liquidity pools", correct_answer: "Cross-border payment connectivity for financial institutions" },
  { question: "What is the difference between Proof of Work and Proof of Stake?", option_a: "PoW uses validators staking tokens; PoS uses computational puzzles", option_b: "PoW uses miners solving computational puzzles; PoS uses validators staking tokens", option_c: "They are identical mechanisms", option_d: "PoW is newer than PoS", correct_answer: "PoW uses miners solving computational puzzles; PoS uses validators staking tokens" },
  { question: "What is MEV (Maximal Extractable Value)?", option_a: "Profit extracted by reordering, inserting, or censoring transactions in a block", option_b: "The maximum coins a miner can ever earn", option_c: "A consensus algorithm", option_d: "A type of smart contract", correct_answer: "Profit extracted by reordering, inserting, or censoring transactions in a block" },
  { question: "What is the 'Blockchain Trilemma'?", option_a: "The challenge of balancing speed, privacy, and governance", option_b: "The tradeoff between decentralization, security, and scalability", option_c: "The problem of mining profitability", option_d: "The difficulty of regulatory compliance", correct_answer: "The tradeoff between decentralization, security, and scalability" },
  { question: "What does 'finality' mean in blockchain?", option_a: "The last block ever mined", option_b: "The point at which a transaction is irreversible and permanently confirmed", option_c: "The final state of a smart contract", option_d: "The end of a blockchain epoch", correct_answer: "The point at which a transaction is irreversible and permanently confirmed" },
  { question: "What is a smart contract?", option_a: "A legal agreement signed digitally", option_b: "Self-executing code stored on a blockchain that runs when predefined conditions are met", option_c: "A type of crypto wallet", option_d: "A centralized database entry", correct_answer: "Self-executing code stored on a blockchain that runs when predefined conditions are met" },
  { question: "What does TVL (Total Value Locked) measure in DeFi?", option_a: "The total number of blockchain transactions", option_b: "The total market cap of all tokens", option_c: "The total value of assets deposited into DeFi protocols", option_d: "The total fees earned by validators", correct_answer: "The total value of assets deposited into DeFi protocols" },
  { question: "What is an oracle in the context of blockchain?", option_a: "A blockchain prediction market", option_b: "A service that brings real-world data onto the blockchain for smart contracts to use", option_c: "A type of consensus node", option_d: "A zero-knowledge proof system", correct_answer: "A service that brings real-world data onto the blockchain for smart contracts to use" },
  { question: "What is a '51% attack'?", option_a: "A phishing attack targeting 51% of users", option_b: "When a single entity controls over half the network's mining or staking power to manipulate the chain", option_c: "A smart contract vulnerability", option_d: "A regulatory action against 51% of exchanges", correct_answer: "When a single entity controls over half the network's mining or staking power to manipulate the chain" },
  { question: "What is the purpose of a zero-knowledge proof (ZKP) in blockchain?", option_a: "To prove identity with a government ID", option_b: "To prove knowledge of information without revealing the information itself", option_c: "To verify a transaction with zero fees", option_d: "To create anonymous wallets only", correct_answer: "To prove knowledge of information without revealing the information itself" },
  { question: "Which of these is an ecosystem hub for Arc where you can find builders, list your project and track everything on chain?", option_a: "Tower Exchange", option_b: "Arc Trivia 1.0", option_c: "Arclens", option_d: "Arc Escrow", correct_answer: "Arclens" },
  { question: "Which of these is the Principal Technical Project Manager for Arc and Circle Developer Programs?", option_a: "Bobbilee Hartman", option_b: "Blessing Adesiji", option_c: "Sam Sealey", option_d: "Timothy Baker", correct_answer: "Bobbilee Hartman" },
  { question: "Which of these is the Circle Lead Community Manager?", option_a: "Sam Sealey", option_b: "Timothy Baker", option_c: "Blessing Adesiji", option_d: "Bobbilee Hartman", correct_answer: "Timothy Baker" },
];

async function seed() {
  console.log("Clearing existing questions...");
  const { error: deleteError } = await supabase.from("questions").delete().neq("id", 0);
  if (deleteError) { console.error("Delete error:", deleteError.message); process.exit(1); }

  console.log(`Seeding ${questions.length} questions...`);
  const { error } = await supabase.from("questions").insert(questions);
  if (error) { console.error("Insert error:", error.message); process.exit(1); }

  console.log(`✅ ${questions.length} questions seeded successfully!`);
}

seed();
